sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: OCWeiRSlwxNVQkLMUvNwbYnx577gqlsL1JqZ5DA9yem5LfNO0nvSQ6Pijo2rff1BETofk7fdxmyOgt5T0KF0Nsvb+u2HA6GsYPZlQHCv4W9/DQeGYKH46qYmb24S6dG68TeiyRS7FqYgUK0r3lREnniOQC3KPtQwf9HnMXUn4sq8K3DAvrO9ISrN0wqJtxVugWeT5z4glgInpu0XpUpZ0QP9wByazGK/qvkVUjNciNs7irKnQycxHa7nYhyGlwHVUvwUskddVH0DY9b0PXDgPSdm0gE5ipLCSE2REOymwWvR1D2tTYhq4umysOaE744dRfCqkFGLfgOUmayh+6+REDXTGRpuTKDEnnC05CvUftmC4k2oXl/bap+b7ztaIp5ZNpNQSBtIYdgAcs1zEwXtRIo9ZtCL4lTPWmldczeVGfx6fxttQb8rkJbnUA/03VCoGSr1otTk5/VJdXYdki4SyojyS+CrQzWkIfHw3gybS8hzPnyg2egrjCuPtbZYlP3UG3Wrh8AwMrUtK8vsdG11I8y2fRkFByGCEQFZNsRU/Ph/fjw9qAeTr3hYM6KPV8Bk8LXkyELxTXa3wuXR7S8gmW0mqHT9qDKcK23kUfhXF3FnrfoN1cgF6yK3qX2ZdQtaUudUn77hi+wnKrA55mLonqAYgV1HbpbVO3cxBlM5pbM=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/A-Legend-of-Montrose_1461
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy